services:
  proxy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ../..           # repo root
      dockerfile: infra/docker/frontend.Dockerfile
    restart: unless-stopped

  backend:
    build:
      context: ../..
      dockerfile: infra/docker/backend.Dockerfile
    restart: unless-stopped

volumes:
  caddy_data: {}
  caddy_config: {}

