version: "3.9"
services:
  web:
    image: caddy:2
    restart: unless-stopped
    ports: ["80:80"]
    volumes:
      - ./../../site:/srv
      - ./../proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data: {}
  caddy_config: {}
